name: Insured Assurance CI Job

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Job Info
        run: echo "Job build_test is executing as part of new workflow - from $owner_name"

      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.8

      - name: Test with Maven
        run: mvn -B test --file pom.xml

      - name: Trigger Jenkins Deployment Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST $JENKINS_URL/job/simplilearn-insured-assurance/build?token=akash-token --user $JENKINS_USER:$JENKINS_API_TOKEN 
